
POST http://localhost:8080/user/reg
Content-Type: application/json

{
  "name": "Ivan",
  "age": 22
}

###

POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "name": "Ivan",
  "age": 22
}

###

POST http://localhost:8080/calc/run?token=-596230609
Content-Type: application/json

{
  "num1": 2 ,
  "op": "*" ,
  "num2": 2

}

###

POST http://localhost:8080/hist/show
Content-Type: application/json

###